export const API_BASE_URL =
  import.meta.env.VITE_API_BASE_URL ?? '/api'

export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: '/auth/login',
    ME: '/auth/me',
  },
  USERS: '/users',
  PRODUCTS: '/products',
  PRODUCTS_LOW_STOCK: '/products/low-stock',
  CATEGORIES: '/categories',
  CUSTOMERS: '/customers',
  SUPPLIERS: '/suppliers',
  SALES: '/sales',
  PURCHASES: '/purchases',
  INVENTORY: {
    ADJUSTMENT_POSITIVE: '/inventory/adjustment/positive',
    ADJUSTMENT_NEGATIVE: '/inventory/adjustment/negative',
    HISTORY: '/inventory/history',
    HISTORY_BY_PRODUCT: (productId: number) => `/inventory/history/${productId}`,
  },
  EXPORT: {
    SALES: '/export/sales',
    PURCHASES: '/export/purchases',
    INVENTORY_ENTRIES: '/export/inventory/entries',
    INVENTORY_EXITS: '/export/inventory/exits',
    INVENTORY_BALANCES: '/export/inventory/balances',
    INVENTORY_ROTATION: '/export/inventory/rotation',
  },
  DASHBOARD: {
    SALES_DAY: '/dashboard/sales/day',
    SALES_MONTH: '/dashboard/sales/month',
    PURCHASES_SUPPLIERS: '/dashboard/purchases/suppliers',
    PURCHASES_SUPPLIERS_PERIOD: '/dashboard/purchases/suppliers/period',
    PURCHASES_MONTH: '/dashboard/purchases/month',
    PURCHASES_TREND: '/dashboard/purchases/trend',
    PRODUCTS_TOP: '/dashboard/products/top',
    PRODUCTS_TOP_PERIOD: '/dashboard/products/top/period',
    PRODUCTS_LOW_ROTATION: '/dashboard/products/low-rotation',
    PRODUCTS_TOTAL: '/dashboard/products/total',
    STOCK_LOW: '/dashboard/stock/low',
    STOCK_TOTAL: '/dashboard/stock/total',
    SALES_TREND: '/dashboard/sales/trend',
    INVENTORY_ENTRIES: '/dashboard/inventory/entries',
    INVENTORY_EXITS: '/dashboard/inventory/exits',
    INVENTORY_SUMMARY: '/dashboard/inventory/summary',
    INVENTORY_REPLENISHMENT: '/dashboard/inventory/replenishment-alerts',
  },
} as const
